name: CI  # Name of the continuous integration workflow

on:
  push:  # Trigger the workflow on a push
    branches:
      - '*'  # Any branch
  pull_request:  # Trigger the workflow on a pull request
    branches:
      - '*'  # Any branch

jobs:
  build:  # Definition of the job called 'build'
    runs-on: ubuntu-latest  # Specifies that the job will run on an Ubuntu environment

    services:
      mongo:  # Configuration for the MongoDB service
        image: mongo:5.0  # MongoDB image to use
        ports:
          - 27017:27017  # Port mapping for MongoDB
        options: >-  # Options to ensure that MongoDB is healthy
          --health-cmd "mongo --eval 'db.runCommand(\"ping\").ok'" 
          --health-interval 10s  
          --health-timeout 5s  
          --health-retries 5  

    steps:  # Steps to be executed in the job
      - name: Checkout code  # Step to check out the code from the repository
        uses: actions/checkout@v3  # Using the checkout action

      - name: Set up Node.js  # Step to set up the Node.js environment
        uses: actions/setup-node@v3  # Using the action to set up Node.js
        with:
          node-version: '20.17.0'  # Specifies the Node.js version to use

      - name: Install dependencies  # Step to install the project dependencies
        run: npm install  # Command to install dependencies

      - name: Set up Docker Buildx  # Step to set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Using the action to set up Buildx

      - name: Set up QEMU  # Step to set up QEMU
        uses: docker/setup-qemu-action@v2  # Using the action to set up QEMU

      - name: Wait for MongoDB to be ready  # Step to wait for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do  # Check if MongoDB port is open
            echo "Waiting for MongoDB...";  # Waiting message
            sleep 5;  # Wait for 5 seconds before checking again
          done

      - name: Run lint  # Step to run lint on the code
        run: timeout 10s npm run lint -- --debug  # Command to run lint with debug information

      - name: Run tests  # Step to run tests
        run: npm test  # Command to run tests

      - name: Build project  # Step to build the project
        run: npm run build  # Command to build the project